#
# A Gradle plugin that supports compiling, testing, assembling and maintaining Modular Multi-Release JAR Files.
#
# Copyright (C) 2019 lingocoder <plugins@lingocoder.com>
#
# This work is licensed under the Creative Commons Attribution-NoDerivatives 4.0
# International (CC BY-ND 4.0) License.
#
# This work is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
# License for more details.
#
# You should have received a copy of the Creative Commons
# Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0) License
# along with this program. To view a copy of this license,
# visit https://creativecommons.org/licenses/by-nd/4.0/.
#

cacheSpec: maximumSize=10000, expireAfterAccess=1h

logging:
  level: DEBUG
  loggers:
    com.alexkudlick.authentication: DEBUG
    io.dropwizard: DEBUG
  appenders:
    - type: console

database:
  driverClass: com.mysql.jdbc.Driver
  url: ${DATABASE_JDBC_URL}
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  checkConnectionOnBorrow: true

